### ISSUE TITLE
rcli cannot create backup: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dohnto** [mhausenblas/reshifter#9]
### What version of Kubernetes (`kubectl  version`) are you using?
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-11T07:11:31Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-11T07:11:31Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

### What version of etcd (`etcdctl --version`) are you using?
```
etcdctl version: 3.1.7
API version: 3.1
```

### What version of ReShifter are you using (for rcli: `rcli version` otherwise at the bottom of the app)?
```
0.3.19
```

### How to reproduce
1. Download binary from github
2. 
```bash
./rcli-linux backup create
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa77db5]

goroutine 1 [running]:
github.com/mhausenblas/reshifter/pkg/backup.backupv3(0xd27ec5, 0x15, 0xc42018ea40, 0x19, 0x0, 0x11, 0x0, 0x0)
	/Users/mhausenblas/Dropbox/dev/work/src/github.com/mhausenblas/reshifter/pkg/backup/backup.go:91 +0x5c5
github.com/mhausenblas/reshifter/pkg/backup.Backup(0xd27ec5, 0x15, 0xc42018ea40, 0x19, 0x0, 0x0, 0x0, 0x0, 0xd18e17, 0x6, ...)
	/Users/mhausenblas/Dropbox/dev/work/src/github.com/mhausenblas/reshifter/pkg/backup/backup.go:51 +0x47c
github.com/mhausenblas/reshifter/rcli/cmd.glob..func1(0x1153560, 0x117bf48, 0x0, 0x0)
	/Users/mhausenblas/Dropbox/dev/work/src/github.com/mhausenblas/reshifter/rcli/cmd/backup.go:32 +0x1f6
github.com/mhausenblas/reshifter/vendor/github.com/spf13/cobra.(*Command).execute(0x1153560, 0x117bf48, 0x0, 0x0, 0x1153560, 0x117bf48)
	/Users/mhausenblas/Dropbox/dev/work/src/github.com/mhausenblas/reshifter/vendor/github.com/spf13/cobra/command.go:651 +0x23a
github.com/mhausenblas/reshifter/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1153de0, 0x117c280, 0xc42000e120, 0xd17c97)
	/Users/mhausenblas/Dropbox/dev/work/src/github.com/mhausenblas/reshifter/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/mhausenblas/reshifter/vendor/github.com/spf13/cobra.(*Command).Execute(0x1153de0, 0xc4201b1f48, 0x47f395)
	/Users/mhausenblas/Dropbox/dev/work/src/github.com/mhausenblas/reshifter/vendor/github.com/spf13/cobra/command.go:685 +0x2b
github.com/mhausenblas/reshifter/rcli/cmd.Execute()
	/Users/mhausenblas/Dropbox/dev/work/src/github.com/mhausenblas/reshifter/rcli/cmd/root.go:25 +0x31
main.main()
	/Users/mhausenblas/Dropbox/dev/work/src/github.com/mhausenblas/reshifter/rcli/main.go:15 +0x4
```

**Comment by mhausenblas** [comment]
@dohnto just cut [v0.3.20](https://github.com/mhausenblas/reshifter/releases/tag/v0.3.20-alpha) which should, fingers crossed, address your issue. Can you please try?

**Comment by dohnto** [comment]
I have build it from source and it works now. Closing.

**Comment by mhausenblas** [comment]
Thank you @dohnto!
